apiVersion: appprotectdos.f5.com/v1beta1
kind: DosProtectedResource
metadata:
 name: dos-protected
spec:
 enable: true
 name: "cafe.example.com"
 apDosPolicy: "dospolicy"
 apDosMonitor:
    uri: "cafe.example.com"
    protocol: "http1"
    timeout: 5
 dosAccessLogDest: "syslog-svc-2.default.svc.cluster.local:514"
 dosSecurityLog:
    enable: true
    apDosLogConf: "doslogconf"
    dosLogDest: "syslog-svc.default.svc.cluster.local:514" 
