apiVersion: "cis.f5.com/v1"
kind: IngressLink
metadata:
  name: vs-ingresslink
  namespace: nginx-ingress
spec:
  virtualServerAddress: "??????" #Replace the ??? with the VS IP. For single NIC BIG-IP instance, this is the self IP.
  iRules:
    - /Common/Proxy_Protocol_iRule
  selector:
    matchLabels:
      app: nginx-ingress 
